---

- name: Install Parsoid node modules locally
  npm:
    global: no
    path: "{{ nodejs_app_install_dir }}"

- name: Set Parsoid settings file
  template:
    dest: "{{ nodejs_app_install_dir }}/settings.json"
    src: settings.json.template
  notify: Restart the application systemd unit

